### ISSUE TITLE
"task is null" inside "tasks" macro

### ISSUE THREAD

**Issue by ClemensRobbenhaar** [xwikisas/application-task#130]
Unfortunately not much information, but in one case the overview of all tasks via the `tasks` macro failed with the error message:

    Failed to execute the [velocity] macro. Cause: [Cannot invoke "com.xwiki.task.model.Task.getReference()" because "task" is null]. Click on this message for details.

Clicking on the message however does not show any details. There is nothing in the logs or in the HTML code of the page (as far as I could see.)  

Maybe this is caused by the code here not checking for null:

https://github.com/xwikisas/application-task/blob/f5db0e6c403484f2dd26ca285ebcf8ab9485e012/application-task-default/src/main/java/com/xwiki/task/internal/macro/TasksMacro.java#L115

while the `DefaultTaskManager.getTask(int)` might return `null` if the document does not contain a task (esp. if it does not exist)
https://github.com/xwikisas/application-task/blob/f5db0e6c403484f2dd26ca285ebcf8ab9485e012/application-task-default/src/main/java/com/xwiki/task/internal/DefaultTaskManager.java#L115

This should not happen, as the query should not return any results, but I have no better explanation. Maybe some bullet proofing (or a different exception in the DefaultTaskManager) would help.

**Comment by ClemensRobbenhaar** [comment]
We were able on a second try to extract the stack trace. I only paste the first 10 lines or so here, as most is "the usual velocity / rendering stuff"

```
java.lang.NullPointerException: Cannot invoke "com.xwiki.task.model.Task.getReference()" because "task" is null
 at com.xwiki.task.internal.macro.TasksMacro.execute(TasksMacro.java:115)
 at com.xwiki.task.internal.macro.TasksMacro.execute(TasksMacro.java:60)
 at org.xwiki.rendering.internal.transformation.macro.MacroTransformation.transform(MacroTransformation.java:311)
 at org.xwiki.rendering.internal.transformation.DefaultRenderingContext.transformInContext(DefaultRenderingContext.java:183)
 at org.xwiki.rendering.internal.transformation.DefaultTransformationManager.performTransformations(DefaultTransformationManager.java:88)
 at org.xwiki.display.internal.DocumentContentAsyncExecutor.executeInCurrentExecutionContext(DocumentContentAsyncExecutor.java:396)
 at org.xwiki.display.internal.DocumentContentAsyncExecutor.execute(DocumentContentAsyncExecutor.java:269)
 at org.xwiki.display.internal.DocumentContentAsyncRenderer.execute(DocumentContentAsyncRenderer.java:112)
 at org.xwiki.rendering.async.internal.block.AbstractBlockAsyncRenderer.render(AbstractBlockAsyncRenderer.java:157)
 at org.xwiki.rendering.async.internal.block.AbstractBlockAsyncRenderer.render(AbstractBlockAsyncRenderer.java:54)
 at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.syncRender(DefaultAsyncRendererExecutor.java:290)
 at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.render(DefaultAsyncRendererExecutor.java:267)
 at org.xwiki.rendering.async.internal.block.DefaultBlockAsyncRendererExecutor.execute(DefaultBlockAsyncRendererExecutor.java:125)
 at org.xwiki.display.internal.DocumentContentDisplayer.display(DocumentContentDisplayer.java:67)
 at org.xwiki.display.internal.DocumentContentDisplayer.display(DocumentContentDisplayer.java:43)
 at org.xwiki.display.internal.DefaultDocumentDisplayer.display(DefaultDocumentDisplayer.java:96)
 at org.xwiki.display.internal.DefaultDocumentDisplayer.display(DefaultDocumentDisplayer.java:39)
 at org.xwiki.sheet.internal.SheetDocumentDisplayer.display(SheetDocumentDisplayer.java:123)
 at org.xwiki.sheet.internal.SheetDocumentDisplayer.display(SheetDocumentDisplayer.java:52)
 at org.xwiki.display.internal.ConfiguredDocumentDisplayer.display(ConfiguredDocumentDisplayer.java:68)
 at org.xwiki.display.internal.ConfiguredDocumentDisplayer.display(ConfiguredDocumentDisplayer.java:42)
 at com.xpn.xwiki.doc.XWikiDocument.display(XWikiDocument.java:1388)
```

**Comment by trrenty** [comment]
This issue should be fixed by #179 

I don't know why we didnt throw an exception before, but now we do. The exception should be caught and this issue shouldn't reproduce anymore. Line with the fix: https://github.com/xwikisas/application-task/blob/f87895c902c8f008f06723cb92e58d6ae5921339/application-task-default/src/main/java/com/xwiki/task/internal/DefaultTaskManager.java#L120-L124
