### ISSUE TITLE
Recursive call of displayTaskAsDependecy make tasks created by normal user unavailable

### ISSUE THREAD

**Issue by petrenkonikita112263** [xwikisas/application-task#47]
**ENVIROMENT**: local XWiki 14.10.14 with Task Manager 3.0.3

**STEPS TO REPRODUCE**

1. install Task Manager Pro
2. obtain trial license
3. create a dedicated space, with name "TestTaskManager"
4. grant view right to this page and its children for XWikiAdminGroup
5. create a dedicated normal user and log in with created account
6. create a simple task by normal user in TaskManager space, logout
7. login as Admin, and create around 100 or more than 100 tasks in "TestTaskManager" space using Task macro or copy/paste the code below

```
{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_1"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_2"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_3"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_4"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_5"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_6"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_7"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_8"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_9"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_10"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_11"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_12"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_13"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_14"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_15"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_16"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_17"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_18"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_19"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_20"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_21"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_22"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_23"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_24"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_25"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_26"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_27"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_28"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_29"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_30"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_31"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_32"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_33"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_34"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_35"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_36"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_37"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_38"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_39"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_40"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_41"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_42"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_43"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_44"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_45"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_46"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_47"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_48"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_49"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_50"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_51"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_52"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_53"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_54"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_55"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_56"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_57"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_58"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_59"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_60"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_61"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_62"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_63"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_64"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_65"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_66"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_67"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_68"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_69"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_70"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_71"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_72"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_73"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_74"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_75"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_76"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_77"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_78"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_79"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_80"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_81"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_82"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_83"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_84"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_85"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_86"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_87"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_88"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_89"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_90"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_91"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_92"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_93"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_94"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_95"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_96"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_97"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_98"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_99"}}{{/task}}

{{task createDate="2023/08/04 11:10" reporter="XWiki.Admin" reference="TestTaskManager.Task_100"}}{{/task}}
```
Finally, perform these steps
1. logout and login as normal user
2. navigate into TaskManager home page and find task created by normal user
3. press "Edit"

**ACTUAL RESULT**
The XWiki will crush, with error in web tab
```
Error number 4001 in 4: Error while evaluating velocity template edit.vm
Error number 4001 in 4: Error while evaluating velocity template edit.vm
com.xpn.xwiki.XWikiException: Error number 4001 in 4: Error while evaluating velocity template edit.vm
	at com.xpn.xwiki.XWiki.evaluateTemplate(XWiki.java:2568)
	at com.xpn.xwiki.web.Utils.parseTemplate(Utils.java:180)
	at com.xpn.xwiki.web.XWikiAction.execute(XWikiAction.java:651)
	at com.xpn.xwiki.web.XWikiAction.execute(XWikiAction.java:339)
	at com.xpn.xwiki.web.LegacyActionServlet.service(LegacyActionServlet.java:114)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1419)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1624)
	at com.xpn.xwiki.web.ActionFilter.doFilter(ActionFilter.java:122)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)
	at org.xwiki.wysiwyg.filter.ConversionFilter.doFilter(ConversionFilter.java:61)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)
	at org.xwiki.container.servlet.filters.internal.SetHTTPHeaderFilter.doFilter(SetHTTPHeaderFilter.java:63)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)
	at org.xwiki.resource.servlet.RoutingFilter.doFilter(RoutingFilter.java:132)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)
	at org.xwiki.container.servlet.filters.internal.SavedRequestRestorerFilter.doFilter(SavedRequestRestorerFilter.java:208)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)
	at org.xwiki.container.servlet.filters.internal.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:111)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:164)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:506)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1378)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1300)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:562)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:418)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:675)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:410)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.xwiki.rendering.RenderingException: Failed to execute renderer
	at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.syncRender(DefaultAsyncRendererExecutor.java:287)
	at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.render(DefaultAsyncRendererExecutor.java:267)
	at org.xwiki.rendering.async.internal.block.DefaultBlockAsyncRendererExecutor.render(DefaultBlockAsyncRendererExecutor.java:154)
	at com.xpn.xwiki.internal.template.InternalTemplateManager.render(InternalTemplateManager.java:843)
	at com.xpn.xwiki.internal.template.InternalTemplateManager.renderFromSkin(InternalTemplateManager.java:805)
	at com.xpn.xwiki.internal.template.InternalTemplateManager.renderFromSkin(InternalTemplateManager.java:785)
	at com.xpn.xwiki.internal.template.InternalTemplateManager.render(InternalTemplateManager.java:771)
	at com.xpn.xwiki.internal.template.DefaultTemplateManager.render(DefaultTemplateManager.java:91)
	at com.xpn.xwiki.internal.template.DefaultTemplateManager.render(DefaultTemplateManager.java:85)
	at com.xpn.xwiki.XWiki.evaluateTemplate(XWiki.java:2563)
	... 62 more
Caused by: org.xwiki.rendering.RenderingException: Failed to evaluate template with id [/skins/flamingo/edit.vm]
	at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.evaluateContent(TemplateAsyncRenderer.java:224)
	at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.renderVelocity(TemplateAsyncRenderer.java:177)
	at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.render(TemplateAsyncRenderer.java:138)
	at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.render(TemplateAsyncRenderer.java:54)
	at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.lambda$syncRender$0(DefaultAsyncRendererExecutor.java:284)
	at com.xpn.xwiki.internal.security.authorization.DefaultAuthorExecutor.call(DefaultAuthorExecutor.java:98)
	at org.xwiki.rendering.async.internal.DefaultAsyncRendererExecutor.syncRender(DefaultAsyncRendererExecutor.java:284)
	... 71 more
Caused by: org.xwiki.velocity.XWikiVelocityException: Failed to evaluate content with namespace [/skins/flamingo/edit.vm]
	at org.xwiki.velocity.internal.DefaultVelocityEngine.evaluate(DefaultVelocityEngine.java:289)
	at com.xpn.xwiki.render.DefaultVelocityManager.evaluate(DefaultVelocityManager.java:321)
	at com.xpn.xwiki.internal.template.VelocityTemplateEvaluator.evaluateContent(VelocityTemplateEvaluator.java:95)
	at com.xpn.xwiki.internal.template.TemplateAsyncRenderer.evaluateContent(TemplateAsyncRenderer.java:222)
	... 77 more
Caused by: java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:101)
	at java.base/java.util.Stack.pop(Stack.java:83)
	at org.apache.velocity.context.InternalContextBase.popCurrentMacroName(InternalContextBase.java:148)
	at org.apache.velocity.context.AbstractContext.popCurrentMacroName(AbstractContext.java:51)
	at org.apache.velocity.context.InternalContextAdapterImpl.popCurrentMacroName(InternalContextAdapterImpl.java:170)
	at org.apache.velocity.runtime.directive.VelocimacroProxy.render(VelocimacroProxy.java:219)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:331)
	at org.apache.velocity.runtime.directive.RuntimeMacro.render(RuntimeMacro.java:261)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:304)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:171)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:147)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:439)
	at org.apache.velocity.runtime.parser.node.ASTIfStatement.render(ASTIfStatement.java:190)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:439)
	at org.apache.velocity.Template.merge(Template.java:358)
	at org.apache.velocity.Template.merge(Template.java:262)
	at org.xwiki.velocity.internal.DefaultVelocityEngine.evaluate(DefaultVelocityEngine.java:280)
	... 80 more
```

**EXPECTED RESULT**
The user can edit his own task without any issues and save updated content.

There's a workaround. The issue won't happen if to unset view right for XWikiAdminGroup on "TestTaskManager".

**Comment by trrenty** [comment]
The server logs display this message
```
2023-08-04 13:14:56,395 [qtp1629911510-2135 - http://192.168.150.86:8080/xwiki/bin/edit/TaskManager/TaskForNormalUser] ERROR o.a.v.macro                    - Max calling depth of 100 was exceeded in macro 'displayTaskAsDependency' with Call Stack:template->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency->displayTaskAsDependency at xwiki:TaskManager.TaskForNormalUser[line 12, column 1]
```
Which suggests that the macro was indeed called recursively. However, [the code](https://github.com/xwikisas/application-task/blob/f34e2a5876229b0af94752790e3890b25b0cf086/application-task-ui/src/main/resources/TaskManager/TaskManagerClass.xml#L116-L158) does not have any recursive call to itself. Having 50 tasks in the forbidden page will not cause the issue to reproduce. The macro will be called 50 times but none will be displayed because the user does not have the rights to see it.

Checking for the viewrights for the dependencies when executing the velocity macro will fix the issue. Another improvement I made was to exclude the tasks that did not have a `project` set, thus eliminating the tasks created inline.

**Comment by petrenkonikita112263** [comment]
Removing #break statement in this [line](https://github.com/xwikisas/application-task/blob/f34e2a5876229b0af94752790e3890b25b0cf086/application-task-ui/src/main/resources/TaskManager/TaskManagerClass.xml#L121) solve the issue and moving this content into if statement 

```
#if("$!task" == '')
  #set($tasktitle = $task.getProperty('name').value)
  #set($tasklink = $services.model.serialize($taskpageref,'compactwiki'))
  #set($taskstatus = $task.getProperty('status').value)
  #set($taskduedate = $task.display('duedate', 'view'))
  #set($taskproject = $task.getProperty('project').value)
#end
  ```
